apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy
# apiVersion: v1
# kind: Service
# metadata:
#  name: reverseproxy-svc
# spec:
#  selector:
#    role: app
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 5000
#      nodePort: 32001
#  type: NodePort